require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.treesitter")
require("user.autopairs")
require("user.telescope")

require("view.colorscheme")
require("view.nvim-tree")
require("view.bufferline")

require("lsp.cmp")
require("lsp.mason")
require("lsp.lspconfig")
require("lsp.lspsaga")
require("lsp.null-ls")
require("user.comment")
